module.exports = {
    repositories: [
        "stackabletech/airflow-operator",
        "stackabletech/beku.py",
        "stackabletech/commons-operator",
        "stackabletech/docker-images",
        "stackabletech/documentation",
        "stackabletech/documentation-ui",
        "stackabletech/druid-operator",
        "stackabletech/hbase-normalizer",
        "stackabletech/hbase-operator",
        "stackabletech/hdfs-operator",
        "stackabletech/hello-world-operator",
        "stackabletech/hive-operator",
        "stackabletech/kafka-operator",
        "stackabletech/listener-operator",
        "stackabletech/nifi-operator",
        "stackabletech/opa-operator",
        "stackabletech/operator-rs",
        "stackabletech/operator-templating",
        "stackabletech/product-config",
        "stackabletech/secret-operator",
        "stackabletech/spark-k8s-operator",
        "stackabletech/stackable-utils",
        "stackabletech/superset-operator",
        "stackabletech/trino-operator",
        "stackabletech/zookeeper-operator",
    ],
    gitAuthor: "\"Stacky McStackface\" <serviceaccounts@stackable.tech>",
    includeForks: true,
    logFileLevel: 'debug',
    logLevel: 'debug',
    recreateClosed: 'true',
    force: {
      schedule: [],
      prCreation: "immediate",
    }
  };
