#!/usr/bin/env bash
set -euo pipefail
PR_BRANCH_NAME=${1:?Must provide name of PR branch to operate on.}
source repos
for product in "${products[@]}"; do
    STATE=$(gh pr view ${PR_BRANCH_NAME}  -R stackabletech/${product}-operator --jq '.state' --json state)
    if [[ $STATE -eq "OPEN" ]]; then
        gh pr close ${PR_BRANCH_NAME} -R stackabletech/${product}-operator
    else
        echo "Skipping ${product}, PR already closed"
    fi
done
