#!/usr/bin/env bash
set -euo pipefail
PR_BRANCH_NAME=${1:?Must provide name of PR branch to operate on.}
source "$(dirname -- "$0")/common"
for product in "${products[@]}"; do
    if [[ -z "$(pr_state "$product" "$PR_BRANCH_NAME")" ]]; then
        echo "Skipping ${product}, no PR for ${PR_BRANCH_NAME}"
        continue
    fi
    gh pr diff "$PR_BRANCH_NAME" -R "stackabletech/${product}-operator"
done
