#!/usr/bin/env bash
set -euo pipefail
PR_BRANCH_NAME=${1:?Must provide name of PR branch to operate on.}
source repos
# Disable gh paging for results.
PAGER=
for product in "${products[@]}"; do
    echo "#### PRs for $product ###"
    gh pr list -R stackabletech/${product}-operator
done
