#!/usr/bin/env bash
set -euo pipefail
source "$(dirname -- "$0")/common"
# Disable gh paging for results. Needs exporting to reach gh.
export PAGER=
for product in "${products[@]}"; do
    echo "#### PRs for $product ###"
    gh pr list -R "stackabletech/${product}-operator"
done
