#!/usr/bin/env bash
PR_BRANCH_NAME=${1:?Must provide name of PR branch to operate on.}
source repos
for product in "${products[@]}"; do
    STATE=$(gh pr view ${PR_BRANCH_NAME}  -R stackabletech/${product}-operator --jq '.state' --json state)
    gh pr checks ${PR_BRANCH_NAME} -R stackabletech/${product}-operator &> /dev/null
    status=$?
    echo "${product}(${STATE}): ${status}"
done
