---
images-repo: docker-images
operators:
  - airflow-operator
  - commons-operator
  - druid-operator
  - hbase-operator
  - hdfs-operator
  - hello-world-operator
  - hive-operator
  - kafka-operator
  - listener-operator
  - nifi-operator
  - opa-operator
  - secret-operator
  - spark-k8s-operator
  - superset-operator
  - trino-operator
  - zookeeper-operator